### ISSUE TITLE
 sorry found a solution -- operator error !! Requires libavutil.so.56 includes only libavutil.so.55

### ISSUE THREAD

**Issue by jdarundell** [snapcrafters/ffmpeg#58]
My snap (or the calling program over which I have no control) is failing with 
Error: Unable to load DLL 'avutil.56': The specified module could not be found.

agent software from iSpyConnect netcore.3.1 with dotnet runtime

I'm happy to add a symlink if only I knew where it is looking

Error:    at FFmpeg.AutoGen.ffmpeg.LoadLibrary(String libraryName, Boolean throwException)
   at FFmpeg.AutoGen.ffmpeg.<>c.<.cctor>b__6_0(String libraryName)
   at FFmpeg.AutoGen.ffmpeg.<>c.<.cctor>b__6_604(Int32 level)
   at FFmpeg.AutoGen.ffmpeg.av_log_set_level(Int32 level)
   at CoreLogic.FFmpeg.SetFfmpegLogging(Int32 loglevel)
   at CoreLogic.FFmpeg.Init()
   at CoreLogic.Threads.StartUp()
Unable to load DLL 'avutil.56': The specified module could not be found.

**Comment by jdarundell** [comment]
Operator error
